<?php
declare(strict_types=1);
require_once __DIR__ . '/ReturnStateMachine.php';
final class ReturnService
{
 public function __construct(private readonly PDO $pdo,private readonly ReturnRepository $repo,private readonly CaseQuantityAvailability $availability,private readonly OrderAccessService $access,private readonly AuditService $audit,private readonly ReturnStateMachine $machine=new ReturnStateMachine(),private readonly int$returnDays=14){}
 public function create(string $public,ActorContext $actor,?string $grant,string $idem,array $input):array
 {
  if($idem===''||strlen($idem)>255)throw new DomainException('Invalid request.');$o=$this->orderForCreate($public,$actor,$grant);$items=$input['items']??[];$req=[];foreach($items as$i){$id=(int)($i['order_item_id']??0);$q=(int)($i['quantity']??0);if($id<1||$q<1||isset($req[$id]))throw new DomainException('Invalid return item.');$req[$id]=$q;}ksort($req);if($req===[]||empty($input['reason_code']))throw new DomainException('Invalid return.');
  $normalized=['reason_code'=>(string)$input['reason_code'],'items'=>$req];$scope=hash('sha256',$actor->type()."\0".$o['id']."\0".($actor->userId()??$grant));$key=hash('sha256',$idem);$hash=hash('sha256',json_encode($normalized,JSON_THROW_ON_ERROR));
  return Transactional::run($this->pdo,function()use($o,$actor,$normalized,$req,$scope,$key,$hash){$old=$this->repo->replay($scope,$key);if($old){if(!hash_equals($old['request_hash'],$hash))throw new DomainException('Idempotency conflict.');return$old;}$locked=$this->availability->lockOrderItems((int)$o['id'],array_keys($req));foreach($locked as$row)if(($row['product_type']??'')!=='physical')throw new DomainException('Digital item cannot be returned.');$this->availability->assertReservable($locked,$req);$r=$this->repo->insert(['public_id'=>bin2hex(random_bytes(16)),'order_id'=>(int)$o['id'],'owner_type'=>$actor->type()==='customer_account'?'account':'guest','owner_user_id'=>$actor->userId(),'reason_code'=>$normalized['reason_code'],'scope'=>$scope,'key'=>$key,'request'=>$hash]);foreach($req as$id=>$q)$this->repo->item((int)$r['id'],(int)$o['id'],$id,$q);$a=AuditActor::fromContext($actor);$c=bin2hex(random_bytes(16));$this->repo->event((int)$r['id'],$a,$c,$key);$this->audit->record(bin2hex(random_bytes(16)),'return',(int)$r['id'],'create','success',$a,$c,null,'requested',[],$key);return$r;});
 }
 public function orderForCreate(string$public,ActorContext$actor,?string$grant):array{$o=$this->repo->order($public);$user=$actor->type()==='customer_account'?['id'=>$actor->userId()]:null;if(!$o||!$this->access->canAccess($o,$user,$grant,false,$public)||($o['status']??null)!=='delivered')throw new DomainException('Order unavailable.');$window=$this->repo->returnWindowStart((int)$o['id']);if($window===null||new DateTimeImmutable($window)<new DateTimeImmutable("-{$this->returnDays} days",new DateTimeZone('UTC')))throw new DomainException('Return request window is closed.');return$o;}
 public function guestOrderPublicId(string$id):string{$o=$this->repo->parentOrder($id);if(!$o)throw new DomainException('Return unavailable.');return(string)$o['public_id'];}
 public function accountList(AuthContext$auth):array{if(!$auth->isAuthenticated()||!$auth->userId())throw new DomainException('Verified account required.');return$this->repo->customerListByOwner($auth->userId());}
 public function detail(string$id,ActorContext$actor,?string$grant):array{$o=$this->repo->parentOrder($id);$u=$actor->type()==='customer_account'?['id'=>$actor->userId()]:null;if(!$o||!$this->access->canAccess($o,$u,$grant,false,(string)$o['public_id']))throw new DomainException('Return unavailable.');return$this->repo->customerDetail($id);}
 public function detailPayload(string$id,ActorContext$actor,?string$grant):array{$events=$this->detail($id,$actor,$grant);if($events===[])throw new DomainException('Return unavailable.');$summary=$events[0];foreach(['action','old_state','new_state','public_message','event_created_at']as$field)unset($summary[$field]);return['summary'=>$summary,'events'=>$events,'items'=>$this->repo->customerItems($id)];}
 public function transition(string$id,ActorContext$actor,int$version,string$target,array$data,string$idem):array
 {
  if($actor->type()!=='legacy_shared_admin'||$idem==='')throw new DomainException('Admin required.');
  return Transactional::run($this->pdo,function()use($id,$actor,$version,$target,$data,$idem){$cur=$this->repo->lockByPublicId($id);if(!$cur)throw new DomainException('Return unavailable.');$key=hash('sha256',$idem);$request=hash('sha256',json_encode([$id,$version,$target,$data],JSON_THROW_ON_ERROR));$replay=$this->repo->transitionReplay((int)$cur['id'],$key);if($replay){if(!hash_equals((string)$replay['request_hash'],$request))throw new DomainException('Idempotency conflict.');return['id'=>$cur['id'],'public_id'=>$id,'status'=>$replay['new_state'],'version'=>$replay['entity_version']];}if((int)$cur['version']!==$version)throw new DomainException('Version conflict.');$old=(string)$cur['status'];$items=$this->repo->items((int)$cur['id']);$itemIds=array_map(static fn($x)=>(int)$x['order_item_id'],$items);$this->availability->lockOrderItems((int)$cur['order_id'],$itemIds);if(in_array($target,['received','inspected'],true)){$field=$target.'_items';$provided=$data[$field]??null;if(!is_array($provided)||$provided===[])throw new DomainException('Item quantities are required.');$normalized=[];foreach($provided as$item=>$q)$normalized[(int)$item]=(int)$q;foreach($items as$item){$itemId=(int)$item['order_item_id'];$max=$target==='received'?(int)$item['requested_quantity']:(int)$item['received_quantity'];if(!isset($normalized[$itemId])||$normalized[$itemId]<0||$normalized[$itemId]>$max)throw new DomainException('Invalid item quantity.');}if($target==='received')$this->repo->setReceived((int)$cur['id'],$normalized);else$this->repo->setInspected((int)$cur['id'],$normalized);}if($target==='completed'){if(($cur['decision']??$data['decision']??null)==='refund'&&(($cur['refund_status']??null)!=='confirmed'||empty($cur['refund_external_id'])||empty($cur['refund_confirmed_at'])))throw new DomainException('Trusted refund evidence is required.');$this->repo->consumeInspected((int)$cur['id']);}$this->machine->assertTransition($old,$target,array_merge($cur,$data));$a=AuditActor::fromContext($actor);$c=bin2hex(random_bytes(16));if($old===$target){$this->repo->eventTransition((int)$cur['id'],'state_noop',$old,$target,$version,$a,$c,$key,$request,isset($data['public_message'])?(string)$data['public_message']:null,isset($data['internal_note'])?(string)$data['internal_note']:null);$this->audit->record(bin2hex(random_bytes(16)),'return',(int)$cur['id'],'state_noop','ignored',$a,$c,$old,$target,[],$key);return$cur;}$updated=$this->repo->transition((int)$cur['id'],$version,$target,$data);$this->repo->eventTransition((int)$cur['id'],'state_transition',$old,$target,(int)$updated['version'],$a,$c,$key,$request,isset($data['public_message'])?(string)$data['public_message']:null,isset($data['internal_note'])?(string)$data['internal_note']:null);$this->audit->record(bin2hex(random_bytes(16)),'return',(int)$cur['id'],'state_transition','success',$a,$c,$old,$target,[],$key);return$updated;});
 }
 public function addCustomerMessage(string$id,ActorContext$actor,?string$grant,string$message,string$idem):array{$message=trim($message);if($message===''||mb_strlen($message)>2000||$idem==='')throw new DomainException('Invalid message.');$order=$this->repo->parentOrder($id);$user=$actor->type()==='customer_account'?['id'=>$actor->userId()]:null;if(!$order||!$this->access->canAccess($order,$user,$grant,false,(string)$order['public_id']))throw new DomainException('Return unavailable.');$key=hash('sha256',$idem);$request=hash('sha256',$message);return Transactional::run($this->pdo,function()use($id,$actor,$message,$key,$request){$case=$this->repo->lockByPublicId($id);if(!$case||in_array($case['status'],['rejected','completed','cancelled'],true))throw new DomainException('Return is closed.');$old=$this->repo->messageReplay((int)$case['id'],$key);if($old){if(!hash_equals((string)$old['request_hash'],$request))throw new DomainException('Idempotency conflict.');return$old;}$a=AuditActor::fromContext($actor);$c=bin2hex(random_bytes(16));$event=$this->repo->insertCustomerMessage((int)$case['id'],(string)$case['status'],$a,$c,$key,$request,$message);$this->audit->record(bin2hex(random_bytes(16)),'return',(int)$case['id'],'customer_message','success',$a,$c,(string)$case['status'],(string)$case['status'],[],$key);return$event;});}
}
