<?php
declare(strict_types=1);
final class ReturnRepository
{
 public function __construct(private readonly PDO $pdo){}
 public static function customerDetailSql():string{return "SELECT r.public_id,r.order_id,r.reason_code,r.status,r.decision,r.refund_status,r.customer_note,r.version,r.created_at,r.updated_at,e.action,e.old_state,e.new_state,e.public_message,e.created_at event_created_at FROM store_returns r LEFT JOIN store_return_events e ON e.return_id=r.id WHERE r.public_id=? ORDER BY e.created_at,e.id";}
 public static function customerItemsSql():string{return 'SELECT ri.order_item_id,oi.product_name,ri.requested_quantity,ri.received_quantity,ri.inspected_quantity,ri.consumed_quantity FROM store_return_items ri JOIN store_returns r ON r.id=ri.return_id JOIN store_order_items oi ON oi.id=ri.order_item_id AND oi.order_id=ri.order_id WHERE r.public_id=? ORDER BY ri.order_item_id';}
 public function customerDetail(string $id):array{$s=$this->pdo->prepare(self::customerDetailSql());$s->execute([$id]);return$s->fetchAll(PDO::FETCH_ASSOC);}
 public function customerItems(string$id):array{$s=$this->pdo->prepare(self::customerItemsSql());$s->execute([$id]);return$s->fetchAll(PDO::FETCH_ASSOC);}
 public function customerListByOwner(string$userId):array{$s=$this->pdo->prepare('SELECT public_id,reason_code,status,decision,refund_status,version,created_at,updated_at,closed_at FROM store_returns WHERE owner_type=\'account\' AND owner_user_id=? ORDER BY created_at DESC,id DESC');$s->execute([$userId]);return$s->fetchAll(PDO::FETCH_ASSOC);}
 public function parentOrder(string $id):?array{$s=$this->pdo->prepare('SELECT o.* FROM store_returns r JOIN store_orders o ON o.id=r.order_id WHERE r.public_id=?');$s->execute([$id]);return$s->fetch(PDO::FETCH_ASSOC)?:null;}
 public function lockByPublicId(string $id):?array{$s=$this->pdo->prepare('SELECT * FROM store_returns WHERE public_id=? FOR UPDATE');$s->execute([$id]);return$s->fetch(PDO::FETCH_ASSOC)?:null;}
 public function transitionReplay(int$id,string$key):?array{$s=$this->pdo->prepare("SELECT request_hash,new_state,entity_version FROM store_return_events WHERE return_id=? AND action IN('state_transition','state_noop') AND idempotency_key_hash=?");$s->execute([$id,$key]);return$s->fetch(PDO::FETCH_ASSOC)?:null;}
 public function messageReplay(int$id,string$key):?array{$s=$this->pdo->prepare("SELECT public_id,request_hash FROM store_return_events WHERE return_id=? AND action='customer_message' AND idempotency_key_hash=?");$s->execute([$id,$key]);return$s->fetch(PDO::FETCH_ASSOC)?:null;}
 public function insertCustomerMessage(int$id,string$status,AuditActor$a,string$c,string$key,string$request,string$message):array{$public=bin2hex(random_bytes(16));$s=$this->pdo->prepare("INSERT INTO store_return_events(public_id,return_id,action,old_state,new_state,actor_type,actor_user_id,actor_session_id,auth_source,public_message,correlation_id,idempotency_key_hash,request_hash)VALUES(?,?,'customer_message',?,?,?,?,?,?,?,?,?,?)");$s->execute([$public,$id,$status,$status,$a->type,$a->userId,$a->sessionId,$a->authSource,$message,$c,$key,$request]);return['public_id'=>$public];}
 public function order(string $id):?array{$s=$this->pdo->prepare('SELECT * FROM store_orders WHERE public_id=?');$s->execute([$id]);return $s->fetch(PDO::FETCH_ASSOC)?:null;}
 public function returnWindowStart(int$orderId):?string{$s=$this->pdo->prepare("SELECT COALESCE(MAX(d.delivered_at),o.updated_at,o.created_at)::text FROM store_orders o LEFT JOIN store_deliveries d ON d.order_id=o.id AND d.status='delivered' WHERE o.id=? GROUP BY o.id,o.updated_at,o.created_at");$s->execute([$orderId]);$v=$s->fetchColumn();return is_string($v)?$v:null;}
 public function replay(string $scope,string $key):?array{$s=$this->pdo->prepare('SELECT id,public_id,request_hash FROM store_returns WHERE idempotency_scope_hash=? AND idempotency_key_hash=?');$s->execute([$scope,$key]);return $s->fetch(PDO::FETCH_ASSOC)?:null;}
 public function insert(array $r):array{$s=$this->pdo->prepare('INSERT INTO store_returns(public_id,order_id,owner_type,owner_user_id,reason_code,idempotency_scope_hash,idempotency_key_hash,request_hash)VALUES(?,?,?,?,?,?,?,?)RETURNING id,public_id,status,version');$s->execute([$r['public_id'],$r['order_id'],$r['owner_type'],$r['owner_user_id'],$r['reason_code'],$r['scope'],$r['key'],$r['request']]);return $s->fetch(PDO::FETCH_ASSOC);}
 public function item(int $rid,int $oid,int $iid,int $q):void{$s=$this->pdo->prepare('INSERT INTO store_return_items(return_id,order_id,order_item_id,requested_quantity)VALUES(?,?,?,?)');$s->execute([$rid,$oid,$iid,$q]);}
 public function event(int $id,AuditActor $a,string $corr,string $key):void{$s=$this->pdo->prepare("INSERT INTO store_return_events(public_id,return_id,action,new_state,actor_type,actor_user_id,actor_session_id,auth_source,public_message,correlation_id,idempotency_key_hash)VALUES(?,?,'created','requested',?,?,?,?,?,?,?)");$s->execute([bin2hex(random_bytes(16)),$id,$a->type,$a->userId,$a->sessionId,$a->authSource,'Žádost o vrácení byla přijata.',$corr,$key]);}
 public function transition(int$id,int$version,string$status,array$data):array{$closed=in_array($status,['rejected','completed','cancelled'],true);$s=$this->pdo->prepare('UPDATE store_returns SET status=?,decision=COALESCE(?,decision),received_at=COALESCE(?,received_at),inspected_at=COALESCE(?,inspected_at),completed_at=COALESCE(?,completed_at),customer_note=COALESCE(?,customer_note),internal_note=COALESCE(?,internal_note),closed_at=CASE WHEN ? THEN now() ELSE closed_at END,updated_at=now(),version=version+1 WHERE id=? AND version=? RETURNING *');$s->execute([$status,$data['decision']??null,$data['received_at']??null,$data['inspected_at']??null,$data['completed_at']??null,$data['public_message']??null,$data['internal_note']??null,$closed?1:0,$id,$version]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!$r)throw new DomainException('Version conflict.');return$r;}
 public function eventTransition(int$id,string$action,string$old,string$new,int$entityVersion,AuditActor$a,string$c,string$key,string$request,?string$public,?string$internal):void{$s=$this->pdo->prepare("INSERT INTO store_return_events(public_id,return_id,action,old_state,new_state,entity_version,actor_type,actor_user_id,actor_session_id,auth_source,public_message,internal_note,correlation_id,idempotency_key_hash,request_hash)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");$s->execute([bin2hex(random_bytes(16)),$id,$action,$old,$new,$entityVersion,$a->type,$a->userId,$a->sessionId,$a->authSource,$public,$internal,$c,$key,$request]);}
 public function items(int$id):array{$s=$this->pdo->prepare('SELECT order_id,order_item_id,requested_quantity,received_quantity,inspected_quantity,consumed_quantity FROM store_return_items WHERE return_id=? ORDER BY order_item_id FOR UPDATE');$s->execute([$id]);return$s->fetchAll(PDO::FETCH_ASSOC);}
 public function setReceived(int$id,array$quantities):void{$s=$this->pdo->prepare('UPDATE store_return_items SET received_quantity=? WHERE return_id=? AND order_item_id=?');foreach($quantities as$item=>$q){$s->execute([$q,$id,$item]);if($s->rowCount()!==1)throw new DomainException('Return item unavailable.');}}
 public function setInspected(int$id,array$quantities):void{$s=$this->pdo->prepare('UPDATE store_return_items SET inspected_quantity=? WHERE return_id=? AND order_item_id=?');foreach($quantities as$item=>$q){$s->execute([$q,$id,$item]);if($s->rowCount()!==1)throw new DomainException('Return item unavailable.');}}
 public function consumeInspected(int$id):void{$s=$this->pdo->prepare('UPDATE store_return_items SET consumed_quantity=inspected_quantity WHERE return_id=? AND consumed_quantity=0');$s->execute([$id]);}
}
