<?php
declare(strict_types=1);
final class DeliveryService
{
 public function __construct(private readonly PDO$pdo,private readonly DeliveryRepository$repo,private readonly DeliveryStateMachine$machine,private readonly TrackingUrlPolicy$tracking,private readonly AuditService$audit){}
 public function create(int$order,ActorContext$actor,array$input,string$idempotencyKey):array
 {
  if($actor->type()!=='legacy_shared_admin'||$idempotencyKey==='')throw new DomainException('Admin required.');$carrier=(string)($input['carrier_code']??'');$url=$input['tracking_url']??null;if(!$this->tracking->isSafe($carrier,is_string($url)?$url:null))throw new DomainException('Unsafe tracking URL.');$req=[];foreach($input['items']??[]as$i){$id=(int)($i['order_item_id']??0);$q=(int)($i['quantity']??0);if($id<1||$q<1||isset($req[$id]))throw new DomainException('Invalid shipment item.');$req[$id]=$q;}ksort($req);if($req===[])throw new DomainException('Shipment items required.');$normalized=['carrier_code'=>$carrier,'tracking_number'=>(string)($input['tracking_number']??''),'tracking_url'=>$url,'items'=>$req];$scope=hash('sha256',$actor->type()."\0".(string)$actor->sessionIdHash()."\0".$order);$key=hash('sha256',$idempotencyKey);$request=hash('sha256',json_encode($normalized,JSON_THROW_ON_ERROR));
  return Transactional::run($this->pdo,function()use($order,$actor,$req,$carrier,$url,$normalized,$scope,$key,$request){$old=$this->repo->replay($scope,$key);if($old){if(!hash_equals((string)$old['request_hash'],$request))throw new DomainException('Idempotency conflict.');return$old;}$rows=$this->repo->lockItems($order,array_keys($req));foreach($req as$id=>$q)if($this->repo->shipped($id)+$q>(int)$rows[$id]['quantity'])throw new DomainException('Shipped quantity exceeds purchase.');$d=$this->repo->create($order,['carrier_code'=>$carrier,'tracking_number'=>$normalized['tracking_number'],'tracking_url'=>$url,'scope'=>$scope,'key'=>$key,'request'=>$request]);foreach($req as$id=>$q)$this->repo->item((int)$d['id'],$order,$id,$q);$a=AuditActor::fromContext($actor);$c=bin2hex(random_bytes(16));$this->repo->event((int)$d['id'],$a,$c);$this->audit->record(bin2hex(random_bytes(16)),'delivery',(int)$d['id'],'create','success',$a,$c,null,'pending',[],$key);return$d;});
 }
 public function transition(string$id,ActorContext$actor,int$version,string$target,array$data,string$idem):array
 {
  if($actor->type()!=='legacy_shared_admin'||$idem==='')throw new DomainException('Admin required.');$url=$data['tracking_url']??null;if($url!==null&&!$this->tracking->isSafe((string)($data['carrier_code']??''),(string)$url))throw new DomainException('Unsafe tracking URL.');
  return Transactional::run($this->pdo,function()use($id,$actor,$version,$target,$data,$idem){$cur=$this->repo->lockByPublicId($id);if(!$cur)throw new DomainException('Delivery unavailable.');$key=hash('sha256',$idem);$request=hash('sha256',json_encode([$id,$version,$target,$data],JSON_THROW_ON_ERROR));$replay=$this->repo->transitionReplay((int)$cur['id'],$key);if($replay){if(!hash_equals((string)$replay['request_hash'],$request))throw new DomainException('Idempotency conflict.');return['id'=>$cur['id'],'public_id'=>$id,'status'=>$replay['new_state'],'version'=>$replay['entity_version']];}if((int)$cur['version']!==$version)throw new DomainException('Version conflict.');$old=(string)$cur['status'];$merged=array_merge($cur,$data);$this->machine->assertTransition($old,$target,$merged);$a=AuditActor::fromContext($actor);$c=bin2hex(random_bytes(16));if($old===$target){$this->repo->eventTransition((int)$cur['id'],'state_noop',$old,$target,$version,$a,$c,$key,$request,isset($data['public_message'])?(string)$data['public_message']:null,isset($data['internal_note'])?(string)$data['internal_note']:null);$this->audit->record(bin2hex(random_bytes(16)),'delivery',(int)$cur['id'],'state_noop','ignored',$a,$c,$old,$target,[],$key);return$cur;}$updated=$this->repo->transition((int)$cur['id'],$version,$target,$data);$this->repo->eventTransition((int)$cur['id'],'state_transition',$old,$target,(int)$updated['version'],$a,$c,$key,$request,isset($data['public_message'])?(string)$data['public_message']:null,isset($data['internal_note'])?(string)$data['internal_note']:null);$this->audit->record(bin2hex(random_bytes(16)),'delivery',(int)$cur['id'],'state_transition','success',$a,$c,$old,$target,[],$key);return$updated;});
 }
 public function customerDetail(string$orderPublic,array$order,ActorContext$actor,?string$grant,OrderAccessService$access):array{$u=$actor->type()==='customer_account'?['id'=>$actor->userId()]:null;if(!$access->canAccess($order,$u,$grant,false,$orderPublic))throw new DomainException('Delivery unavailable.');$rows=$this->repo->customerByOrder($orderPublic);foreach($rows as&$row)if(!$this->tracking->isSafe((string)($row['carrier_code']??''),isset($row['tracking_url'])?(string)$row['tracking_url']:null))$row['tracking_url']=null;return$rows;}
}
