<?php
declare(strict_types=1);
final class DeliveryRepository
{
 public function __construct(private readonly PDO $pdo){}
 public function lockItems(int $order,array $ids):array{$ids=array_values(array_unique(array_map('intval',$ids)));sort($ids);$m=implode(',',array_fill(0,count($ids),'?'));$s=$this->pdo->prepare("SELECT id,quantity FROM store_order_items WHERE order_id=? AND id IN($m) ORDER BY id FOR UPDATE");$s->execute([$order,...$ids]);$r=[];foreach($s->fetchAll(PDO::FETCH_ASSOC)as$x)$r[(int)$x['id']]=$x;if(count($r)!==count($ids))throw new DomainException('Order item unavailable.');return$r;}
 public function shipped(int $item):int{$s=$this->pdo->prepare("SELECT COALESCE(SUM(di.shipped_quantity),0) FROM store_delivery_items di JOIN store_deliveries d ON d.id=di.delivery_id WHERE di.order_item_id=? AND d.status<>'cancelled'");$s->execute([$item]);return(int)$s->fetchColumn();}
 public function replay(string$scope,string$key):?array{$s=$this->pdo->prepare('SELECT id,public_id,status,version,request_hash FROM store_deliveries WHERE idempotency_scope_hash=? AND idempotency_key_hash=?');$s->execute([$scope,$key]);return$s->fetch(PDO::FETCH_ASSOC)?:null;}
 public function create(int $order,array $d):array{$s=$this->pdo->prepare('INSERT INTO store_deliveries(public_id,order_id,carrier_code,tracking_number,tracking_url,idempotency_scope_hash,idempotency_key_hash,request_hash)VALUES(?,?,?,?,?,?,?,?)RETURNING id,public_id,status,version');$s->execute([bin2hex(random_bytes(16)),$order,$d['carrier_code'],$d['tracking_number'],$d['tracking_url'],$d['scope'],$d['key'],$d['request']]);return$s->fetch(PDO::FETCH_ASSOC);}
 public function item(int $delivery,int $order,int $item,int $q):void{$s=$this->pdo->prepare('INSERT INTO store_delivery_items(delivery_id,order_id,order_item_id,shipped_quantity)VALUES(?,?,?,?)');$s->execute([$delivery,$order,$item,$q]);}
 public function event(int$id,AuditActor$a,string$c):void{$s=$this->pdo->prepare("INSERT INTO store_delivery_events(public_id,delivery_id,action,new_state,actor_type,actor_user_id,actor_session_id,auth_source,public_message,correlation_id)VALUES(?,?,'created','pending',?,?,?,?,?,?)");$s->execute([bin2hex(random_bytes(16)),$id,$a->type,$a->userId,$a->sessionId,$a->authSource,'Zásilka byla založena.',$c]);}
 public function lockByPublicId(string$id):?array{$s=$this->pdo->prepare('SELECT * FROM store_deliveries WHERE public_id=? FOR UPDATE');$s->execute([$id]);return$s->fetch(PDO::FETCH_ASSOC)?:null;}
 public function transitionReplay(int$id,string$key):?array{$s=$this->pdo->prepare("SELECT request_hash,new_state,entity_version FROM store_delivery_events WHERE delivery_id=? AND action IN('state_transition','state_noop') AND idempotency_key_hash=?");$s->execute([$id,$key]);return$s->fetch(PDO::FETCH_ASSOC)?:null;}
 public function transition(int$id,int$version,string$status,array$data):array{$s=$this->pdo->prepare('UPDATE store_deliveries SET status=?,carrier_code=COALESCE(?,carrier_code),tracking_number=COALESCE(?,tracking_number),tracking_url=COALESCE(?,tracking_url),shipped_at=COALESCE(?,shipped_at),estimated_delivery_at=COALESCE(?,estimated_delivery_at),delivered_at=COALESCE(?,delivered_at),customer_message=COALESCE(?,customer_message),internal_note=COALESCE(?,internal_note),last_updated_at=now(),updated_at=now(),version=version+1 WHERE id=? AND version=? RETURNING *');$s->execute([$status,$data['carrier_code']??null,$data['tracking_number']??null,$data['tracking_url']??null,$data['shipped_at']??null,$data['estimated_delivery_at']??null,$data['delivered_at']??null,$data['public_message']??null,$data['internal_note']??null,$id,$version]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!$r)throw new DomainException('Version conflict.');return$r;}
 public function eventTransition(int$id,string$action,string$old,string$new,int$entityVersion,AuditActor$a,string$c,string$key,string$request,?string$public,?string$internal):void{$s=$this->pdo->prepare("INSERT INTO store_delivery_events(public_id,delivery_id,action,old_state,new_state,entity_version,actor_type,actor_user_id,actor_session_id,auth_source,public_message,internal_note,correlation_id,idempotency_key_hash,request_hash)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");$s->execute([bin2hex(random_bytes(16)),$id,$action,$old,$new,$entityVersion,$a->type,$a->userId,$a->sessionId,$a->authSource,$public,$internal,$c,$key,$request]);}
 public function customerByOrder(string$orderPublic):array{$s=$this->pdo->prepare('SELECT d.public_id,d.carrier_code,d.carrier_name,d.shipping_method,d.tracking_number,d.tracking_url,d.shipped_at,d.estimated_delivery_at,d.delivered_at,d.last_updated_at,d.status,d.customer_message,d.version FROM store_deliveries d JOIN store_orders o ON o.id=d.order_id WHERE o.public_id=? ORDER BY d.created_at,d.id');$s->execute([$orderPublic]);return$s->fetchAll(PDO::FETCH_ASSOC);}
}
