<?php
declare(strict_types=1);
require_once __DIR__.'/../testlib.php';foreach(['auth/ActorContext','orders/OrderAccessService','database/Transactional','audit/AuditActor','audit/AuditService','attachments/LocalPrivateStorage','attachments/AttachmentRepository','attachments/AttachmentService']as$f)require_once __DIR__.'/../../lib/'.$f.'.php';
$dsn=getenv('VEVIT_STORE_TEST_DSN');$u=getenv('VEVIT_STORE_TEST_DB_USER');$p=getenv('VEVIT_STORE_TEST_DB_PASS');if($dsn===false||$u===false||$p===false)exit(77);if(!preg_match('/test/i',$dsn))exit(1);$pdo=new PDO($dsn,$u,$p,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$pdo->exec('DROP TABLE IF EXISTS store_case_attachments,store_delivery_events,store_delivery_items,store_deliveries,store_return_events,store_return_items,store_returns,store_claim_events,store_claim_items,store_claims,store_product_favorites,store_audit_events CASCADE');$pdo->exec((string)file_get_contents(__DIR__.'/task-0-4-base-schema.sql'));foreach(['202607290001_checkout_snapshot_up.sql','202607290002_order_access_and_download_grants_up.sql','202607290003_payments_and_inventory_up.sql','202607300002_customer_agenda_up.sql']as$m)$pdo->exec((string)file_get_contents(__DIR__.'/../../migrations/'.$m));
$pdo->exec("INSERT INTO store_products(id,name,slug,price,type,stock)VALUES(1,'A','a',10,'physical',1)");$g='guest';$pdo->prepare("INSERT INTO store_orders(id,order_number,public_id,guest_grant_hash,guest_grant_expires_at,status,total,currency,customer_email,customer_name)VALUES(1,'O1',?,?,NOW()+INTERVAL '1 day','paid',10,'czk','g@x.test','G')")->execute([str_repeat('a',32),hash('sha256',$g)]);$pdo->prepare("INSERT INTO store_claims(id,public_id,order_id,owner_type,reason_code,problem_description,requested_resolution,idempotency_scope_hash,idempotency_key_hash,request_hash)VALUES(1,?,1,'guest','x','x','repair',?,?,?)")->execute([str_repeat('b',32),str_repeat('1',64),str_repeat('2',64),str_repeat('3',64)]);
$root=sys_get_temp_dir().'/vevit-case-storage-'.bin2hex(random_bytes(4));mkdir($root,0700,true);$tmp=tempnam(sys_get_temp_dir(),'vv');file_put_contents($tmp,"\xFF\xD8\xFF\xE0".str_repeat('A',32));$storage=new LocalPrivateStorage($root,['image/jpeg'],1024,null);$s=new AttachmentService($pdo,new AttachmentRepository($pdo),$storage,new OrderAccessService(new DateTimeImmutable('now',new DateTimeZone('UTC'))),new AuditService($pdo),5);$a=new ActorContext('customer_guest',null,null,'guest_order_grant');
try{$s->upload('claim',str_repeat('b',32),$a,$g,'double-ext',$tmp,'evil.php.jpg');test_assert_true(false,'dangerous double extension is rejected');}catch(DomainException){}
$r=$s->upload('claim',str_repeat('b',32),$a,$g,'up1',$tmp,'evidence.jpg');test_assert_true(strlen($r['public_id'])===32,'attachment has public id');test_assert_same(1,(int)$pdo->query('SELECT COUNT(*) FROM store_case_attachments')->fetchColumn(),'metadata inserted');test_assert_same(1,(int)$pdo->query("SELECT COUNT(*) FROM store_claim_events WHERE action='attachment_uploaded'")->fetchColumn(),'domain event inserted');
$metadata=$s->authorizeDownload((string)$r['public_id'],$a,$g);test_assert_true(!isset($metadata['absolute_path']),'authorized metadata exposes no absolute path');
$pdo->prepare('UPDATE store_case_attachments SET revoked_at=now() WHERE public_id=?')->execute([$r['public_id']]);try{$s->authorizeDownload((string)$r['public_id'],$a,$g);test_assert_true(false,'revoked attachment cannot be downloaded');}catch(DomainException){}
$pdo->exec("CREATE OR REPLACE FUNCTION reject_attachment_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'test audit failure'; END $$;CREATE TRIGGER reject_attachment_audit BEFORE INSERT ON store_audit_events FOR EACH ROW EXECUTE FUNCTION reject_attachment_audit()");
$tmp2=tempnam(sys_get_temp_dir(),'vv');file_put_contents($tmp2,"\xFF\xD8\xFF\xE0".str_repeat('B',32));try{$s->upload('claim',str_repeat('b',32),$a,$g,'up2',$tmp2,'second.jpg');test_assert_true(false,'audit failure rolls back upload');}catch(PDOException){}
test_assert_same(1,(int)$pdo->query('SELECT COUNT(*) FROM store_case_attachments')->fetchColumn(),'failed audit rolls back attachment metadata');
$files=0;$iterator=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS));foreach($iterator as$file)if($file->isFile())$files++;test_assert_same(1,$files,'failed database transaction cleans stored file');
$pdo->exec('DROP TRIGGER reject_attachment_audit ON store_audit_events;DROP FUNCTION reject_attachment_audit()');
$pdo->exec("UPDATE store_claims SET status='resolved' WHERE id=1");$closedTmp=tempnam(sys_get_temp_dir(),'vv');file_put_contents($closedTmp,"\xFF\xD8\xFF\xE0".str_repeat('D',32));try{$s->upload('claim',str_repeat('b',32),$a,$g,'closed-case',$closedTmp,'closed.jpg');test_assert_true(false,'closed case rejects new attachments');}catch(DomainException){}@unlink($closedTmp);
$pdo->prepare("INSERT INTO store_orders(id,order_number,public_id,guest_grant_hash,guest_grant_expires_at,status,total,currency,customer_email,customer_name)VALUES(2,'O2',?,?,NOW()+INTERVAL '1 day','paid',10,'czk','x@x.test','X')")->execute([str_repeat('c',32),hash('sha256','other-grant')]);
$pdo->prepare("INSERT INTO store_claims(id,public_id,order_id,owner_type,reason_code,problem_description,requested_resolution,idempotency_scope_hash,idempotency_key_hash,request_hash)VALUES(2,?,2,'guest','x','x','repair',?,?,?)")->execute([str_repeat('d',32),str_repeat('4',64),str_repeat('5',64),str_repeat('6',64)]);
$tmp3=tempnam(sys_get_temp_dir(),'vv');file_put_contents($tmp3,"\xFF\xD8\xFF\xE0".str_repeat('C',32));try{$s->upload('claim',str_repeat('d',32),$a,$g,'foreign',$tmp3,'foreign.jpg');test_assert_true(false,'guest cannot upload to a foreign claim');}catch(DomainException){}@unlink($tmp3);
test_complete('attachment-service-postgres-test');
