<?php
declare(strict_types=1);
$dsn=getenv('VEVIT_STORE_TEST_DSN');$user=getenv('VEVIT_STORE_TEST_DB_USER');$pass=getenv('VEVIT_STORE_TEST_DB_PASS');
if($dsn===false||$user===false||$pass===false||!preg_match('/test/i',$dsn))exit(1);
$pdo=new PDO($dsn,$user,$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
$pdo->exec('DROP TABLE IF EXISTS store_case_attachments,store_delivery_events,store_delivery_items,store_deliveries,store_return_events,store_return_items,store_returns,store_claim_events,store_claim_items,store_claims,store_product_favorites,store_audit_events CASCADE');
$pdo->exec((string)file_get_contents(__DIR__.'/task-0-4-base-schema.sql'));
foreach(['202607290001_checkout_snapshot_up.sql','202607290002_order_access_and_download_grants_up.sql','202607290003_payments_and_inventory_up.sql','202607300002_customer_agenda_up.sql']as$m)$pdo->exec((string)file_get_contents(__DIR__.'/../../migrations/'.$m));
$grant='guest-http-grant';$pdo->exec("INSERT INTO store_products(id,name,slug,price,type,stock)VALUES(1,'Test product','test-product',100,'physical',3)");
$s=$pdo->prepare("INSERT INTO store_orders(id,order_number,public_id,guest_grant_hash,guest_grant_expires_at,status,payment_status,fulfillment_status,total,currency,customer_email,customer_name)VALUES(1,'HTTP-1',?,?,NOW()+INTERVAL '1 day','delivered','paid','fulfilled',100,'czk','guest@example.test','Guest')");$s->execute([str_repeat('a',32),hash('sha256',$grant)]);
$pdo->exec("INSERT INTO store_order_items(id,order_id,product_id,product_name,product_type,quantity,unit_price)VALUES(1,1,1,'Test product','physical',2,100)");
$pdo->exec("INSERT INTO store_claims(id,public_id,order_id,owner_type,reason_code,problem_description,requested_resolution,internal_note,idempotency_scope_hash,idempotency_key_hash,request_hash)VALUES(1,repeat('b',32),1,'guest','damaged','Broken','repair','TOP SECRET CLAIM',repeat('1',64),repeat('2',64),repeat('3',64));INSERT INTO store_claim_items(claim_id,order_id,order_item_id,requested_quantity)VALUES(1,1,1,1)");
$pdo->exec("INSERT INTO store_claim_events(public_id,claim_id,action,new_state,actor_type,auth_source,public_message,internal_note,correlation_id)VALUES(repeat('e',32),1,'created','submitted','customer_guest','guest_order_grant','Přijato','TOP SECRET EVENT',repeat('f',32))");
$pdo->exec("INSERT INTO store_case_attachments(public_id,claim_id,owner_type,storage_provider,storage_key,stored_filename,original_filename,detected_mime,byte_size,sha256,scan_status,idempotency_scope_hash,idempotency_key_hash,request_hash)VALUES(repeat('a1',16),1,'guest','local_private','case-attachments/aa/bb/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.jpg','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.jpg','evidence.jpg','image/jpeg',36,repeat('a',64),'not_configured',repeat('b',64),repeat('c',64),repeat('d',64))");
$pdo->exec("INSERT INTO store_returns(id,public_id,order_id,owner_type,reason_code,internal_note,idempotency_scope_hash,idempotency_key_hash,request_hash)VALUES(1,repeat('c',32),1,'guest','unwanted','TOP SECRET RETURN',repeat('4',64),repeat('5',64),repeat('6',64));INSERT INTO store_return_items(return_id,order_id,order_item_id,requested_quantity)VALUES(1,1,1,1)");
$pdo->exec("INSERT INTO store_deliveries(id,public_id,order_id,carrier_code,tracking_number,status,delivered_at,internal_note,idempotency_scope_hash,idempotency_key_hash,request_hash)VALUES(1,repeat('d',32),1,'ppl','TRACK-1','delivered',now(),'TOP SECRET DELIVERY',repeat('7',64),repeat('8',64),repeat('9',64));INSERT INTO store_delivery_items(delivery_id,order_id,order_item_id,shipped_quantity)VALUES(1,1,1,1)");
$pdo->exec("SELECT setval(pg_get_serial_sequence('store_claims','id'),(SELECT max(id) FROM store_claims),true),setval(pg_get_serial_sequence('store_returns','id'),(SELECT max(id) FROM store_returns),true),setval(pg_get_serial_sequence('store_deliveries','id'),(SELECT max(id) FROM store_deliveries),true),setval(pg_get_serial_sequence('store_case_attachments','id'),(SELECT max(id) FROM store_case_attachments),true)");
echo json_encode(['order'=>str_repeat('a',32),'claim'=>str_repeat('b',32),'return'=>str_repeat('c',32),'grant'=>$grant]);
