<?php
declare(strict_types=1);
require_once __DIR__.'/../testlib.php';
foreach(['auth/ActorContext','orders/OrderAccessService','orders/CaseQuantityAvailability','database/Transactional','audit/AuditActor','audit/AuditService','returns/ReturnRepository','returns/ReturnService'] as $f)require_once __DIR__.'/../../lib/'.$f.'.php';
$dsn=getenv('VEVIT_STORE_TEST_DSN');$u=getenv('VEVIT_STORE_TEST_DB_USER');$p=getenv('VEVIT_STORE_TEST_DB_PASS');if($dsn===false||$u===false||$p===false){exit(77);}if(!preg_match('/test/i',$dsn))exit(1);
$pdo=new PDO($dsn,$u,$p,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$pdo->exec('DROP TABLE IF EXISTS store_case_attachments,store_delivery_events,store_delivery_items,store_deliveries,store_return_events,store_return_items,store_returns,store_claim_events,store_claim_items,store_claims,store_product_favorites,store_audit_events CASCADE');$pdo->exec((string)file_get_contents(__DIR__.'/task-0-4-base-schema.sql'));foreach(['202607290001_checkout_snapshot_up.sql','202607290002_order_access_and_download_grants_up.sql','202607290003_payments_and_inventory_up.sql','202607300002_customer_agenda_up.sql']as$m)$pdo->exec((string)file_get_contents(__DIR__.'/../../migrations/'.$m));
$pdo->exec("INSERT INTO store_products(id,name,slug,price,type,stock)VALUES(1,'A','a',10,'physical',5)");$g='guest';$pdo->prepare("INSERT INTO store_orders(id,order_number,public_id,guest_grant_hash,guest_grant_expires_at,status,total,currency,customer_email,customer_name)VALUES(1,'O1',?,?,NOW()+INTERVAL '1 day','delivered',10,'czk','g@x.test','G')")->execute([str_repeat('b',32),hash('sha256',$g)]);$pdo->exec("INSERT INTO store_order_items(id,order_id,product_id,product_name,product_type,quantity,unit_price)VALUES(1,1,1,'A','physical',1,10)");
$s=new ReturnService($pdo,new ReturnRepository($pdo),new CaseQuantityAvailability($pdo),new OrderAccessService(new DateTimeImmutable('now',new DateTimeZone('UTC'))),new AuditService($pdo));$a=new ActorContext('customer_guest',null,null,'guest_order_grant');$in=['reason_code'=>'unwanted','items'=>[['order_item_id'=>1,'quantity'=>1]]];
$pdo->exec("UPDATE store_orders SET created_at=now()-INTERVAL '20 days',updated_at=now()-INTERVAL '20 days' WHERE id=1");try{$s->create(str_repeat('b',32),$a,$g,'expired-window',$in);test_assert_true(false,'configured return window is enforced server-side');}catch(DomainException){}$pdo->exec("UPDATE store_orders SET updated_at=now() WHERE id=1");
$x=$s->create(str_repeat('b',32),$a,$g,'r1',$in);$y=$s->create(str_repeat('b',32),$a,$g,'r1',$in);test_assert_same($x['public_id'],$y['public_id'],'return replay is idempotent');try{$s->create(str_repeat('b',32),$a,$g,'r1',['reason_code'=>'different','items'=>[['order_item_id'=>1,'quantity'=>1]]]);test_assert_true(false,'return idempotency payload conflict is rejected');}catch(DomainException){}try{$s->create(str_repeat('b',32),$a,$g,'r2',['reason_code'=>'too_many','items'=>[['order_item_id'=>1,'quantity'=>2]]]);test_assert_true(false,'return cannot exceed purchased quantity');}catch(DomainException){}try{$s->create(str_repeat('b',32),$a,'wrong','r3',$in);test_assert_true(false,'foreign guest grant is rejected');}catch(DomainException){}test_assert_same(1,(int)$pdo->query('SELECT COUNT(*) FROM store_return_events')->fetchColumn(),'return event written');test_assert_same(1,(int)$pdo->query('SELECT COUNT(*) FROM store_audit_events')->fetchColumn(),'return audit written');test_complete('return-service-postgres-test');
