<?php
declare(strict_types=1);
final class AttachmentRepository
{
 public function __construct(private readonly PDO$pdo){}
 public static function customerListSql(string$type):string
 {if(!in_array($type,['claim','return'],true))throw new InvalidArgumentException('Invalid case type.');$column=$type.'_id';return "SELECT public_id,original_filename,detected_mime,byte_size,scan_status,uploaded_at,revoked_at,deleted_at FROM store_case_attachments WHERE {$column}=? AND revoked_at IS NULL AND deleted_at IS NULL ORDER BY uploaded_at,id";}
 public function customerList(string$type,int$id):array{$s=$this->pdo->prepare(self::customerListSql($type));$s->execute([$id]);return$s->fetchAll(PDO::FETCH_ASSOC);}
 public function parent(string$type,string$public):?array
 {if($type==='claim')$sql='SELECT c.id case_id,c.order_id,c.owner_type,c.owner_user_id,c.status case_status,o.* FROM store_claims c JOIN store_orders o ON o.id=c.order_id WHERE c.public_id=?';elseif($type==='return')$sql='SELECT r.id case_id,r.order_id,r.owner_type,r.owner_user_id,r.status case_status,o.* FROM store_returns r JOIN store_orders o ON o.id=r.order_id WHERE r.public_id=?';else throw new InvalidArgumentException('Invalid case type.');$s=$this->pdo->prepare($sql);$s->execute([$public]);return$s->fetch(PDO::FETCH_ASSOC)?:null;}
 public function lockParent(string$type,int$id):void{$table=$type==='claim'?'store_claims':'store_returns';$s=$this->pdo->prepare("SELECT id FROM {$table} WHERE id=? FOR UPDATE");$s->execute([$id]);if(!$s->fetch())throw new DomainException('Case unavailable.');}
 public function count(string$type,int$id):int{$col=$type.'_id';$s=$this->pdo->prepare("SELECT COUNT(*) FROM store_case_attachments WHERE {$col}=? AND deleted_at IS NULL");$s->execute([$id]);return(int)$s->fetchColumn();}
 public function replay(string$scope,string$key):?array{$s=$this->pdo->prepare('SELECT id,public_id,request_hash FROM store_case_attachments WHERE idempotency_scope_hash=? AND idempotency_key_hash=?');$s->execute([$scope,$key]);return$s->fetch(PDO::FETCH_ASSOC)?:null;}
 public function insert(string$type,int$caseId,ActorContext$actor,array$f,string$scope,string$key,string$request):array{$claim=$type==='claim'?$caseId:null;$return=$type==='return'?$caseId:null;$s=$this->pdo->prepare('INSERT INTO store_case_attachments(public_id,claim_id,return_id,owner_type,owner_user_id,storage_provider,storage_key,stored_filename,original_filename,detected_mime,byte_size,sha256,idempotency_scope_hash,idempotency_key_hash,request_hash)VALUES(?,?,?,?,?,\'local_private\',?,?,?,?,?,?,?,?,?) RETURNING id,public_id');$s->execute([bin2hex(random_bytes(16)),$claim,$return,$actor->type()==='customer_account'?'account':'guest',$actor->userId(),$f['key'],$f['stored_filename'],$f['original_filename'],$f['mime'],$f['bytes'],$f['sha256'],$scope,$key,$request]);return$s->fetch(PDO::FETCH_ASSOC);}
 public function caseEvent(string$type,int$id,AuditActor$a,string$c,string$key):void{$table=$type==='claim'?'store_claim_events':'store_return_events';$column=$type.'_id';$s=$this->pdo->prepare("INSERT INTO {$table}(public_id,{$column},action,actor_type,actor_user_id,actor_session_id,auth_source,public_message,correlation_id,idempotency_key_hash)VALUES(?,?,'attachment_uploaded',?,?,?,?,?,?,?)");$s->execute([bin2hex(random_bytes(16)),$id,$a->type,$a->userId,$a->sessionId,$a->authSource,'Příloha byla nahrána.',$c,$key]);}
 /** @return array<string,mixed>|null */ public function authorizedMetadata(string$public):?array{$s=$this->pdo->prepare('SELECT a.*,COALESCE(c.order_id,r.order_id) order_id,o.public_id order_public_id,o.user_id,o.guest_grant_hash,o.guest_grant_expires_at FROM store_case_attachments a LEFT JOIN store_claims c ON c.id=a.claim_id LEFT JOIN store_returns r ON r.id=a.return_id JOIN store_orders o ON o.id=COALESCE(c.order_id,r.order_id) WHERE a.public_id=?');$s->execute([$public]);return$s->fetch(PDO::FETCH_ASSOC)?:null;}
}
