<?php
declare(strict_types=1);
final class AttachmentService
{
 public function __construct(private readonly PDO$pdo,private readonly AttachmentRepository$repo,private readonly LocalPrivateStorage$storage,private readonly OrderAccessService$access,private readonly AuditService$audit,private readonly int$maxFiles){}
 public static function requestHash(string$type,string$case,string$name,string$mime,int$bytes,string$sha):string{return hash('sha256',json_encode([$type,$case,$name,$mime,$bytes,$sha],JSON_THROW_ON_ERROR));}
 public function guestOrderPublicId(string$type,string$casePublic):string{$p=$this->repo->parent($type,$casePublic);if(!$p)throw new DomainException('Case unavailable.');return(string)$p['public_id'];}
 public function guestOrderPublicIdForAttachment(string$public):string{$m=$this->repo->authorizedMetadata($public);if(!$m)throw new DomainException('Attachment unavailable.');return(string)$m['order_public_id'];}
 public function upload(string$type,string$casePublic,ActorContext$actor,?string$grant,string$idem,string$tmp,string$original):array
 {
  $parent=$this->repo->parent($type,$casePublic);$user=$actor->type()==='customer_account'?['id'=>$actor->userId()]:null;if(!$parent||!$this->access->canAccess($parent,$user,$grant,false,(string)$parent['public_id']))throw new DomainException('Case unavailable.');$closed=$type==='claim'?['rejected','resolved','cancelled']:['rejected','completed','cancelled'];if(in_array((string)($parent['case_status']??''),$closed,true))throw new DomainException('Case is closed.');if($idem===''||!is_file($tmp))throw new DomainException('Invalid upload.');$bytes=(int)filesize($tmp);$mime=(new finfo(FILEINFO_MIME_TYPE))->file($tmp);$sha=hash_file('sha256',$tmp);$request=self::requestHash($type,$casePublic,$original,(string)$mime,$bytes,$sha);$scope=hash('sha256',$actor->type()."\0".$parent['order_id']."\0".($actor->userId()??$grant));$key=hash('sha256',$idem);$storedKey=null;
  try{return Transactional::run($this->pdo,function()use($type,$parent,$actor,$scope,$key,$request,$tmp,$original,&$storedKey){$old=$this->repo->replay($scope,$key);if($old){if(!hash_equals($old['request_hash'],$request))throw new DomainException('Idempotency conflict.');return$old;}$this->repo->lockParent($type,(int)$parent['case_id']);if($this->repo->count($type,(int)$parent['case_id'])>=$this->maxFiles)throw new DomainException('Attachment limit reached.');$file=$this->storage->store($tmp,$original);$file['original_filename']=basename(str_replace('\\','/',$original));$storedKey=$file['key'];$row=$this->repo->insert($type,(int)$parent['case_id'],$actor,$file,$scope,$key,$request);$a=AuditActor::fromContext($actor);$c=bin2hex(random_bytes(16));$this->repo->caseEvent($type,(int)$parent['case_id'],$a,$c,$key);$this->audit->record(bin2hex(random_bytes(16)),'attachment',(int)$row['id'],'upload','success',$a,$c,null,null,['mime'=>$file['mime'],'bytes'=>$file['bytes'],'sha256'=>$file['sha256']],$key);return$row;});}catch(Throwable$e){if($storedKey!==null)$this->storage->remove($storedKey);throw$e;}
 }
 public function authorizeDownload(string$public,ActorContext$actor,?string$grant):array
 {
  $m=$this->repo->authorizedMetadata($public);$user=$actor->type()==='customer_account'?['id'=>$actor->userId()]:null;$order=$m?array_merge($m,['public_id'=>$m['order_public_id']]):null;if(!$m||$m['revoked_at']!==null||$m['deleted_at']!==null||!in_array($m['scan_status'],['not_configured','clean'],true)||!$this->access->canAccess($order,$user,$grant,false,(string)$m['order_public_id']))throw new DomainException('Attachment unavailable.');return$m;
 }
 public function list(string$type,string$casePublic,ActorContext$actor,?string$grant):array{$parent=$this->repo->parent($type,$casePublic);$user=$actor->type()==='customer_account'?['id'=>$actor->userId()]:null;if(!$parent||!$this->access->canAccess($parent,$user,$grant,false,(string)$parent['public_id']))throw new DomainException('Case unavailable.');return$this->repo->customerList($type,(int)$parent['case_id']);}
}
